services:
  backend:
    build: ./eea.docker.plone-climateadapt
    entrypoint: sh -c "tail -f /dev/null"

  converter:
    build: ./volto-blocks-converter
    volumes:
      - ./volto-blocks-converter/app:/app/app
      - ./volto-blocks-converter/requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    entrypoint: sh -c "tail -f /dev/null"

  frontend:
    entrypoint: sh -c "tail -f /dev/null"
